# Generated by Django 2.1.3 on 2018-11-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Compra')),
                ('dataCompra', models.DateField(auto_now=True, verbose_name='Data da Compra')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conta', verbose_name='Conta Vinculada')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('dataVencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('pagamento', models.BooleanField(default=False, verbose_name='Pago?')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Despesa', verbose_name='Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Responsavel', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipoDespesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.TipoDespesa', verbose_name='Tipo de Despesa'),
        ),
    ]
